name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Solidity coverage
        run: npm run coverage
        # By default solidity-coverage generates:
        # coverage/ (HTML) + coverage/lcov.info + coverage.json

      - name: Upload coverage artifacts (HTML + JSON + LCOV)
        uses: actions/upload-artifact@v4
        with:
          name: solidity-coverage
          path: |
            coverage/
            coverage.json
            coverage/lcov.info

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: |
            coverage/lcov.info
            coverage.json
          flags: solidity,hardhat
          name: solidity-coverage
          fail_ci_if_error: true
          verbose: true

      - name: Publish coverage summary
        shell: bash
        run: |
          echo "## ✅ Solidity Coverage Report" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          if [ -f coverage.json ]; then
            echo '```json' >> "$GITHUB_STEP_SUMMARY"
            head -n 50 coverage.json >> "$GITHUB_STEP_SUMMARY"
            echo '```' >> "$GITHUB_STEP_SUMMARY"
            echo "" >> "$GITHUB_STEP_SUMMARY"
            echo "_Full HTML report is available in the uploaded artifact 'solidity-coverage'._" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "_coverage.json not found; see artifact 'solidity-coverage' for full HTML report._" >> "$GITHUB_STEP_SUMMARY"
            echo "⚠️ coverage.json not found!" >> "$GITHUB_STEP_SUMMARY"
          fi
