name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run Solidity coverage
        run: npm run coverage

      - name: Upload coverage artifacts (HTML + JSON)
        uses: actions/upload-artifact@v4
        with:
          name: solidity-coverage
          path: |
            coverage/
            coverage.json

      - name: Publish coverage summary
        run: |
          echo "## Solidity Coverage" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -f coverage.json ]; then
            echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
            head -n 200 coverage.json >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "_coverage.json not found; see artifact ‘solidity-coverage’ for full HTML report._" >> $GITHUB_STEP_SUMMARY
          fi
