name: pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: List test files (debug)
        run: |
          echo "----- test specs -----"
          ls -laR test || true

      - name: Build merged Mochawesome HTML from ALL tests
        run: npm run test:report

      - name: Show found mochawesome JSON (debug)
        run: |
          echo "----- reports tree -----"
          ls -laR reports || true

      - name: Upload docs/ (artifact for Pages)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

      - name: Upload raw reports (debug artifact)
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-raw
          path: reports/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
